<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"  
  "http://www.w3.org/TR/html4/loose.dtd">  
<html > 
<head><title>The raise statement</title> 
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
<meta name="generator" content="TeX4ht (http://www.cse.ohio-state.edu/~gurari/TeX4ht/)"> 
<meta name="originator" content="TeX4ht (http://www.cse.ohio-state.edu/~gurari/TeX4ht/)"> 
<!-- html,4,png,sections+,fn-in --> 
<meta name="src" content="ref.tex"> 
<meta name="date" content="2017-09-28 14:25:00"> 
<link rel="stylesheet" type="text/css" href="ref.css"> 
</head><body 
>
<!--l. 11905--><div class="crosslinks"><p class="noindent">[<a 
href="refse113.html" >next</a>] [<a 
href="#tailrefse112.html">tail</a>] [<a 
href="refch17.html#refse112.html" >up</a>] </p></div>
<h3 class="sectionHead"><span class="titlemark">17.1   </span> <a 
href="ref.html#QQ2-227-265" id="x227-24900017.1">The raise statement</a></h3>
<a 
 id="dx227-249001"></a>
<a 
 id="dx227-249002"></a>
<!--l. 11907--><p class="noindent" ><a name="keyword_raise"></a> The <span 
class="cmtt-10">raise </span>statement is as follows:
     <div class="quote">
     <!--l. 1--><p class="noindent" >_________________________________________________________________________________________________________<br 
class="newline" /><span 
class="cmbx-10">Raise statement</span><br 
class="newline" /><BR/><img 
src="ref212x.png" alt="--raise statement-raise---------------------------------------------
                     - exception instance-|----------------|
                                      -exception address--
     " ><BR/>
                                                                            

                                                                            
     <BR/><img 
src="ref213x.png" alt="--              -  -              -------------------------------
  exception address  at  exception address -,- address expression-|
     " ><BR/>
     ___________________________________________________________________</div>
<!--l. 11910--><p class="noindent" >This statement will raise an exception. If it is specified, the exception instance must be an
initialized instance of any class, which is the raise type. The exception address and frame are
optional. If they are not specified, the compiler will provide the address by itself. If the exception
instance is omitted, then the current exception is re-raised. This construct can only be used in an
exception handling block (see further).
<!--l. 11917--><p class="noindent" ><span 
class="cmbx-10">Remark:</span> Control <span 
class="cmti-10">never </span>returns after an exception block. The control is transferred to the first
<span 
class="cmtt-10">try...finally </span>or <span 
class="cmtt-10">try...except </span>statement that is encountered when unwinding the stack. If no
such statement is found, the Free Pascal Run-Time Library will generate a run-time error 217 (see
also section <a 
href="refse116.html#x231-25300017.5">17.5<!--tex4ht:ref: se:exceptclasses --></a>, page <a 
href="refse116.html#x231-25300017.5">860<!--tex4ht:ref: se:exceptclasses --></a>). The exception address will be printed by the default exception
handling routines.
<!--l. 11925--><p class="noindent" >As an example: The following division checks whether the denominator is zero, and if so, raises an
exception of type <span 
class="cmtt-10">EDivException</span>
                                                                            

                                                                            
<div class="verbatim" id="verbatim-497">
Type&#x00A0;EDivException&#x00A0;=&#x00A0;Class(Exception);
&#x00A0;<br />Function&#x00A0;DoDiv&#x00A0;(X,Y&#x00A0;:&#x00A0;Longint)&#x00A0;:&#x00A0;Integer;
&#x00A0;<br />begin
&#x00A0;<br />&#x00A0;&#x00A0;If&#x00A0;Y=0&#x00A0;then
&#x00A0;<br />&#x00A0;&#x00A0;&#x00A0;&#x00A0;Raise&#x00A0;EDivException.Create&#x00A0;(&#8217;Division&#x00A0;by&#x00A0;Zero&#x00A0;would&#x00A0;occur&#8217;);
&#x00A0;<br />&#x00A0;&#x00A0;Result&#x00A0;:=&#x00A0;X&#x00A0;Div&#x00A0;Y;
&#x00A0;<br />end;
</div>
<!--l. 11935--><p class="nopar" >The class <span 
class="cmtt-10">Exception </span>is defined in the <span 
class="cmss-10">Sysutils </span>unit of the rtl. (section <a 
href="refse116.html#x231-25300017.5">17.5<!--tex4ht:ref: se:exceptclasses --></a>, page <a 
href="refse116.html#x231-25300017.5">860<!--tex4ht:ref: se:exceptclasses --></a>)
<!--l. 11939--><p class="noindent" ><span 
class="cmbx-10">Remark:</span> Although the <span 
class="cmtt-10">Exception </span>class is used as the base class for exceptions throughout the code, this is
just an unwritten agreement: the class can be of any type, and need not be a descendent of the
<span 
class="cmtt-10">Exception </span>class.
<!--l. 11944--><p class="noindent" >Of course, most code depends on the unwritten agreement that an exception class descends from
<span 
class="cmtt-10">Exception</span>.
<!--l. 11948--><p class="noindent" >The following code shows how to omit an error reporting routine from the stack shown in the
exception handler:
                                                                            

                                                                            
<div class="verbatim" id="verbatim-498">
{$mode&#x00A0;objfpc}
&#x00A0;<br />uses&#x00A0;sysutils;
&#x00A0;<br />
&#x00A0;<br />procedure&#x00A0;error(Const&#x00A0;msg&#x00A0;:&#x00A0;string);
&#x00A0;<br />
&#x00A0;<br />begin
&#x00A0;<br />&#x00A0;&#x00A0;raise&#x00A0;exception.create(Msg)&#x00A0;at
&#x00A0;<br />&#x00A0;&#x00A0;&#x00A0;&#x00A0;get_caller_addr(get_frame),
&#x00A0;<br />&#x00A0;&#x00A0;&#x00A0;&#x00A0;get_caller_frame(get_frame);
&#x00A0;<br />end;
&#x00A0;<br />
&#x00A0;<br />procedure&#x00A0;test2;
&#x00A0;<br />
&#x00A0;<br />begin
&#x00A0;<br />&#x00A0;&#x00A0;error(&#8217;Error&#8217;);
&#x00A0;<br />end;
&#x00A0;<br />
&#x00A0;<br />begin
&#x00A0;<br />&#x00A0;&#x00A0;test2;
&#x00A0;<br />end.
</div>
<!--l. 11971--><p class="nopar" >The program, when run, will show a backtrace as follows:
                                                                            

                                                                            
<div class="verbatim" id="verbatim-499">
An&#x00A0;unhandled&#x00A0;exception&#x00A0;occurred&#x00A0;at&#x00A0;$00000000004002D3&#x00A0;:
&#x00A0;<br />Exception&#x00A0;:&#x00A0;Error
&#x00A0;<br />&#x00A0;&#x00A0;$00000000004002D3&#x00A0;line&#x00A0;15&#x00A0;of&#x00A0;testme.pp
&#x00A0;<br />&#x00A0;&#x00A0;$00000000004002E6&#x00A0;line&#x00A0;19&#x00A0;of&#x00A0;testme.pp
</div>
<!--l. 11978--><p class="nopar" >Line 15 is in procedure <span 
class="cmtt-10">Test2</span>, not in <span 
class="cmtt-10">Error</span>, which actually raised the exception.
                                                                            

                                                                            
<!--l. 11983--><div class="crosslinks"><p class="noindent">[<a 
href="refse113.html" >next</a>] [<a 
href="refse112.html" >front</a>] [<a 
href="refch17.html#refse112.html" >up</a>] </p></div>
<!--l. 11983--><p class="noindent" ><a 
 id="tailrefse112.html"></a>  
</body></html> 
